name: Build and publish to Google Play Store

on:
  push:
    branches: [master]

jobs:
  build_and_deploy:
    name: Build and Deploy to Google Play Store
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: get_version
        run: |
          echo "::set-output name=version::$(cat pubspec.yaml | grep version | cut -d: -f2 | tr -d ' ')"
      - name: Flutter Build
        uses: AcmeSoftwareLLC/flutter-build@v1.0.2
        with:
          platform: android
          build-name: ${{ steps.get_version.outputs.version }}
          build-number: ${{ github.run_number }}
          pub-get: true
      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: ar.com.sumit
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: production
