name: Publish to Play Store

on:
  workflow_run:
    workflows: ["Build Android App Bundle"]
    types:
      - completed
    branches: [master]

jobs:
  publish:
    name: Publish to Play Store
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download App Bundle
        uses: actions/download-artifact@v3
        with:
          name: app-bundle
          path: build/app/outputs/bundle/release

      - name: Download Debug Symbols
        uses: actions/download-artifact@v3
        with:
          name: debug-symbols
          path: build/outputs/bundle/release

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: ar.com.sumit
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: production
          status: draft
